services:
  jira-script:
    build: .
    env_file: ".env"
    volumes:
      - ./reports:/app/reports
      - ${JIRA_FILES_PATH}:/app/attachments
    environment:
      JIRA_FILES_PATH: "/app/attachments"
    network_mode: host
